SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `mysqldb_name`;
CREATE TABLE `mysqldb_name` (
  `id` int(100) NOT NULL AUTO_INCREMENT,
  `rlsname` text NOT NULL,
  `grp` text NOT NULL,
  `section` text NOT NULL,
  `ctime` text NOT NULL,
  `files` text DEFAULT NULL,
  `size` text DEFAULT NULL,
  `exact_info` text DEFAULT NULL,
  `exact_files` text DEFAULT NULL,
  `exact_size` text DEFAULT NULL,
  `genre` text DEFAULT NULL,
  `lien_url` text DEFAULT NULL,
  `m3uname` text DEFAULT NULL,
  `nfoname` text DEFAULT NULL,
  `nfosize` text DEFAULT NULL,
  `sfvname` text DEFAULT NULL,
  `sfvsize` text DEFAULT NULL,
  `nuke_status` text DEFAULT NULL,
  `nuke_ctime` text DEFAULT NULL,
  `nuke_reason` text DEFAULT NULL,
  `nuke_net` text DEFAULT NULL,
  `rls_status` text DEFAULT NULL,
  `rls_nick` text DEFAULT NULL,
  `rls_chan` text DEFAULT NULL,
  `rls_network` text DEFAULT NULL,
  `rls_source` text DEFAULT NULL,
  `vid_aspect` text DEFAULT NULL,
  `vid_codec` text DEFAULT NULL,
  `vid_fps` text DEFAULT NULL,
  `vid_res` text DEFAULT NULL,
  `audio_chs` text DEFAULT NULL,
  `audio_codec` text DEFAULT NULL,
  `audio_kbps` text DEFAULT NULL,
  `audio_rate` text DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
