version: '3.8'
networks:
    db:
        driver: bridge

services:
  preedb0t:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Update 'VARIANT' to pick a version of PHP version: 8, 8.1, 8.0, 7, 7.4
        # Append -bullseye or -buster to pin to an OS version.
        # Use -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "bullseye"
        UPGRADE_PACKAGES: "true"
        ADD_NON_FREE_PACKAGES: "true"
        INSTALL_OH_MYS: "true"
        INSTALL_ZSH: "true"
        
    volumes:
      - ./workspace:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: service:db

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyPassW0RDpr3
      MYSQL_USER:  PREEDb0t
      MYSQL_PASSWORD: MyPassW0RDpr3
    expose:
        - "40000"
    ports:
        - "40000:3306"
    volumes:
     - ./data/mariadb:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      db:

  adminer:
    image: adminer
    restart: always
    expose:
      - "40002"
    ports:
      - 40002:8080
    networks:
      db:

  ngircd:
    image: lscr.io/linuxserver/ngircd:latest
    restart: unless-stopped
    volumes:
      - ./data/ngircd:/config
    expose:
      - "6667"
    ports:
      - 6667:6667
  eggdrop:
    image: eggdrop:develop
### If running for the first time without providing your own config, you
### probably want to set these variables
    environment: 
     - SERVER=irc.qczone.name +7000
     - NICK=PREEDb0t
### Make this match your listen setting in the config
    ports:
     - "5000:3333"
### Change this to the path with your config and user/channel files
    volumes:
     - ./data/eggdrop:/home/eggdrop/eggdrop/data/
### If you want to add scripts, put them here. Don't mount to /scripts because
### it will overwrite the ones that are already used. Make sure you use 
### 'source scripts2/foo.tcl' as the path in the config.
#     -/changethispart/scripts:/home/eggdrop/eggdrop/scripts2
### Enter config name, if not eggdrop.conf
#    command: LeafBlower.conf
    # stdin_open: true
    # tty: true
    # restart: always